# =============================================================================
# CONTINUATION METHOD PARAMETERS FOR CONVERGENCE
# =============================================================================

continuation:
  wall_temperature_stable: 3000
  edge_temperature_stable: 5905.5
  pressure_stable: 7000

# =============================================================================
# BASE MODE
# =============================================================================

base:
  enabled: true
  simulation:
    body_type: axisymmetric
    only_stagnation_point: false
    finite_thickness: false
    diffusion_type: stefan_maxwell
    consider_thermal_diffusion: false
    consider_dufour_effect: false
    chemical_mode: non_equilibrium
    catalytic_wall: false
    wall_mode: imposed_temperature
  numerical:
    n_eta: 20
    eta_max: 6.0
    convergence_tolerance: 1.0e-09
    max_iterations: 100000
  mixture:
    name: CO2_5
    thermodynamic_database: RRHO
    viscosity_algorithm: chapman_enskog_ldlt
    thermal_conductivity_algorithm: chapman_enskog_ldlt
    state_model: ChemNonEq1T
  output:
    x_stations:
    - 0.0
    - 0.001
    - 0.002
    - 0.003
    - 0.004
    - 0.005
    - 0.006
    - 0.007
    - 0.008
    - 0.009000000000000001
    - 0.01
    - 0.011
    - 0.012
    - 0.013000000000000001
    - 0.014
    - 0.015
    - 0.016
    - 0.017
    - 0.018000000000000002
    - 0.019
    - 0.02
    - 0.021
    - 0.022
    - 0.023
    - 0.024
    - 0.025
    - 0.026000000000000002
    - 0.027
    - 0.028
    - 0.029
    - 0.03
    - 0.031
    - 0.032
    - 0.033
    - 0.034
    - 0.035
    - 0.036000000000000004
    - 0.037
    - 0.038
    - 0.039
    - 0.04
    - 0.041
    - 0.042
    - 0.043000000000000003
    - 0.044
    - 0.045
    - 0.046
    - 0.047
    - 0.048
    - 0.049
    - 0.05
    - 0.051000000000000004
    - 0.052000000000000005
    - 0.053
    - 0.054
    - 0.055
    - 0.056
    - 0.057
    - 0.058
    - 0.059000000000000004
    - 0.06
    - 0.061
    - 0.062
    - 0.063
    - 0.064
    - 0.065
    - 0.066
    - 0.067
    - 0.068
    - 0.069
    - 0.07
    - 0.07100000000000001
    - 0.07200000000000001
    - 0.073
    - 0.074
    - 0.075
    - 0.076
    - 0.077
    - 0.078
    - 0.079
    - 0.08
    - 0.081
    - 0.082
    - 0.083
    - 0.084
    - 0.085
    - 0.08600000000000001
    - 0.08700000000000001
    - 0.088
    - 0.089
    - 0.09
    - 0.091
    - 0.092
    - 0.093
    - 0.094
    - 0.095
    - 0.096
    - 0.097
    - 0.098
    - 0.099
    - 0.1
    output_directory: test_outputs
  outer_edge:
    edge_points:
    - x: 0.0
      radius: 1.0
      velocity: 0.0
      temperature: 5905.5
      pressure: 7000.0
    - x: 0.001
      radius: 1.0
      velocity: 0.0
      temperature: 5896.445
      pressure: 7000.0
    - x: 0.002
      radius: 1.0
      velocity: 0.0
      temperature: 5887.39
      pressure: 7000.0
    - x: 0.003
      radius: 1.0
      velocity: 0.0
      temperature: 5878.335
      pressure: 7000.0
    - x: 0.004
      radius: 1.0
      velocity: 0.0
      temperature: 5869.28
      pressure: 7000.0
    - x: 0.005
      radius: 1.0
      velocity: 0.0
      temperature: 5860.225
      pressure: 7000.0
    - x: 0.006
      radius: 1.0
      velocity: 0.0
      temperature: 5851.17
      pressure: 7000.0
    - x: 0.007
      radius: 1.0
      velocity: 0.0
      temperature: 5842.115
      pressure: 7000.0
    - x: 0.008
      radius: 1.0
      velocity: 0.0
      temperature: 5833.06
      pressure: 7000.0
    - x: 0.009000000000000001
      radius: 1.0
      velocity: 0.0
      temperature: 5824.005
      pressure: 7000.0
    - x: 0.01
      radius: 1.0
      velocity: 0.0
      temperature: 5814.95
      pressure: 7000.0
    - x: 0.011
      radius: 1.0
      velocity: 0.0
      temperature: 5805.895
      pressure: 7000.0
    - x: 0.012
      radius: 1.0
      velocity: 0.0
      temperature: 5796.84
      pressure: 7000.0
    - x: 0.013000000000000001
      radius: 1.0
      velocity: 0.0
      temperature: 5787.785
      pressure: 7000.0
    - x: 0.014
      radius: 1.0
      velocity: 0.0
      temperature: 5778.73
      pressure: 7000.0
    - x: 0.015
      radius: 1.0
      velocity: 0.0
      temperature: 5769.675
      pressure: 7000.0
    - x: 0.016
      radius: 1.0
      velocity: 0.0
      temperature: 5760.62
      pressure: 7000.0
    - x: 0.017
      radius: 1.0
      velocity: 0.0
      temperature: 5751.565
      pressure: 7000.0
    - x: 0.018000000000000002
      radius: 1.0
      velocity: 0.0
      temperature: 5742.51
      pressure: 7000.0
    - x: 0.019
      radius: 1.0
      velocity: 0.0
      temperature: 5733.455
      pressure: 7000.0
    - x: 0.02
      radius: 1.0
      velocity: 0.0
      temperature: 5724.4
      pressure: 7000.0
    - x: 0.021
      radius: 1.0
      velocity: 0.0
      temperature: 5715.345
      pressure: 7000.0
    - x: 0.022
      radius: 1.0
      velocity: 0.0
      temperature: 5706.29
      pressure: 7000.0
    - x: 0.023
      radius: 1.0
      velocity: 0.0
      temperature: 5697.235
      pressure: 7000.0
    - x: 0.024
      radius: 1.0
      velocity: 0.0
      temperature: 5688.18
      pressure: 7000.0
    - x: 0.025
      radius: 1.0
      velocity: 0.0
      temperature: 5679.125
      pressure: 7000.0
    - x: 0.026000000000000002
      radius: 1.0
      velocity: 0.0
      temperature: 5670.07
      pressure: 7000.0
    - x: 0.027
      radius: 1.0
      velocity: 0.0
      temperature: 5661.015
      pressure: 7000.0
    - x: 0.028
      radius: 1.0
      velocity: 0.0
      temperature: 5651.96
      pressure: 7000.0
    - x: 0.029
      radius: 1.0
      velocity: 0.0
      temperature: 5642.905
      pressure: 7000.0
    - x: 0.03
      radius: 1.0
      velocity: 0.0
      temperature: 5633.85
      pressure: 7000.0
    - x: 0.031
      radius: 1.0
      velocity: 0.0
      temperature: 5624.795
      pressure: 7000.0
    - x: 0.032
      radius: 1.0
      velocity: 0.0
      temperature: 5615.74
      pressure: 7000.0
    - x: 0.033
      radius: 1.0
      velocity: 0.0
      temperature: 5606.685
      pressure: 7000.0
    - x: 0.034
      radius: 1.0
      velocity: 0.0
      temperature: 5597.63
      pressure: 7000.0
    - x: 0.035
      radius: 1.0
      velocity: 0.0
      temperature: 5588.575
      pressure: 7000.0
    - x: 0.036000000000000004
      radius: 1.0
      velocity: 0.0
      temperature: 5579.52
      pressure: 7000.0
    - x: 0.037
      radius: 1.0
      velocity: 0.0
      temperature: 5570.465
      pressure: 7000.0
    - x: 0.038
      radius: 1.0
      velocity: 0.0
      temperature: 5561.41
      pressure: 7000.0
    - x: 0.039
      radius: 1.0
      velocity: 0.0
      temperature: 5552.355
      pressure: 7000.0
    - x: 0.04
      radius: 1.0
      velocity: 0.0
      temperature: 5543.3
      pressure: 7000.0
    - x: 0.041
      radius: 1.0
      velocity: 0.0
      temperature: 5534.245
      pressure: 7000.0
    - x: 0.042
      radius: 1.0
      velocity: 0.0
      temperature: 5525.19
      pressure: 7000.0
    - x: 0.043000000000000003
      radius: 1.0
      velocity: 0.0
      temperature: 5516.135
      pressure: 7000.0
    - x: 0.044
      radius: 1.0
      velocity: 0.0
      temperature: 5507.08
      pressure: 7000.0
    - x: 0.045
      radius: 1.0
      velocity: 0.0
      temperature: 5498.025
      pressure: 7000.0
    - x: 0.046
      radius: 1.0
      velocity: 0.0
      temperature: 5488.97
      pressure: 7000.0
    - x: 0.047
      radius: 1.0
      velocity: 0.0
      temperature: 5479.915
      pressure: 7000.0
    - x: 0.048
      radius: 1.0
      velocity: 0.0
      temperature: 5470.86
      pressure: 7000.0
    - x: 0.049
      radius: 1.0
      velocity: 0.0
      temperature: 5461.805
      pressure: 7000.0
    - x: 0.05
      radius: 1.0
      velocity: 0.0
      temperature: 5452.75
      pressure: 7000.0
    - x: 0.051000000000000004
      radius: 1.0
      velocity: 0.0
      temperature: 5443.695
      pressure: 7000.0
    - x: 0.052000000000000005
      radius: 1.0
      velocity: 0.0
      temperature: 5434.64
      pressure: 7000.0
    - x: 0.053
      radius: 1.0
      velocity: 0.0
      temperature: 5425.585
      pressure: 7000.0
    - x: 0.054
      radius: 1.0
      velocity: 0.0
      temperature: 5416.53
      pressure: 7000.0
    - x: 0.055
      radius: 1.0
      velocity: 0.0
      temperature: 5407.475
      pressure: 7000.0
    - x: 0.056
      radius: 1.0
      velocity: 0.0
      temperature: 5398.42
      pressure: 7000.0
    - x: 0.057
      radius: 1.0
      velocity: 0.0
      temperature: 5389.365
      pressure: 7000.0
    - x: 0.058
      radius: 1.0
      velocity: 0.0
      temperature: 5380.31
      pressure: 7000.0
    - x: 0.059000000000000004
      radius: 1.0
      velocity: 0.0
      temperature: 5371.255
      pressure: 7000.0
    - x: 0.06
      radius: 1.0
      velocity: 0.0
      temperature: 5362.2
      pressure: 7000.0
    - x: 0.061
      radius: 1.0
      velocity: 0.0
      temperature: 5353.145
      pressure: 7000.0
    - x: 0.062
      radius: 1.0
      velocity: 0.0
      temperature: 5344.09
      pressure: 7000.0
    - x: 0.063
      radius: 1.0
      velocity: 0.0
      temperature: 5335.035
      pressure: 7000.0
    - x: 0.064
      radius: 1.0
      velocity: 0.0
      temperature: 5325.98
      pressure: 7000.0
    - x: 0.065
      radius: 1.0
      velocity: 0.0
      temperature: 5316.925
      pressure: 7000.0
    - x: 0.066
      radius: 1.0
      velocity: 0.0
      temperature: 5307.87
      pressure: 7000.0
    - x: 0.067
      radius: 1.0
      velocity: 0.0
      temperature: 5298.8150000000005
      pressure: 7000.0
    - x: 0.068
      radius: 1.0
      velocity: 0.0
      temperature: 5289.76
      pressure: 7000.0
    - x: 0.069
      radius: 1.0
      velocity: 0.0
      temperature: 5280.705
      pressure: 7000.0
    - x: 0.07
      radius: 1.0
      velocity: 0.0
      temperature: 5271.65
      pressure: 7000.0
    - x: 0.07100000000000001
      radius: 1.0
      velocity: 0.0
      temperature: 5262.595
      pressure: 7000.0
    - x: 0.07200000000000001
      radius: 1.0
      velocity: 0.0
      temperature: 5253.54
      pressure: 7000.0
    - x: 0.073
      radius: 1.0
      velocity: 0.0
      temperature: 5244.485
      pressure: 7000.0
    - x: 0.074
      radius: 1.0
      velocity: 0.0
      temperature: 5235.43
      pressure: 7000.0
    - x: 0.075
      radius: 1.0
      velocity: 0.0
      temperature: 5226.375
      pressure: 7000.0
    - x: 0.076
      radius: 1.0
      velocity: 0.0
      temperature: 5217.32
      pressure: 7000.0
    - x: 0.077
      radius: 1.0
      velocity: 0.0
      temperature: 5208.265
      pressure: 7000.0
    - x: 0.078
      radius: 1.0
      velocity: 0.0
      temperature: 5199.21
      pressure: 7000.0
    - x: 0.079
      radius: 1.0
      velocity: 0.0
      temperature: 5190.155
      pressure: 7000.0
    - x: 0.08
      radius: 1.0
      velocity: 0.0
      temperature: 5181.1
      pressure: 7000.0
    - x: 0.081
      radius: 1.0
      velocity: 0.0
      temperature: 5172.045
      pressure: 7000.0
    - x: 0.082
      radius: 1.0
      velocity: 0.0
      temperature: 5162.99
      pressure: 7000.0
    - x: 0.083
      radius: 1.0
      velocity: 0.0
      temperature: 5153.935
      pressure: 7000.0
    - x: 0.084
      radius: 1.0
      velocity: 0.0
      temperature: 5144.88
      pressure: 7000.0
    - x: 0.085
      radius: 1.0
      velocity: 0.0
      temperature: 5135.825
      pressure: 7000.0
    - x: 0.08600000000000001
      radius: 1.0
      velocity: 0.0
      temperature: 5126.77
      pressure: 7000.0
    - x: 0.08700000000000001
      radius: 1.0
      velocity: 0.0
      temperature: 5117.715
      pressure: 7000.0
    - x: 0.088
      radius: 1.0
      velocity: 0.0
      temperature: 5108.66
      pressure: 7000.0
    - x: 0.089
      radius: 1.0
      velocity: 0.0
      temperature: 5099.605
      pressure: 7000.0
    - x: 0.09
      radius: 1.0
      velocity: 0.0
      temperature: 5090.55
      pressure: 7000.0
    - x: 0.091
      radius: 1.0
      velocity: 0.0
      temperature: 5081.495
      pressure: 7000.0
    - x: 0.092
      radius: 1.0
      velocity: 0.0
      temperature: 5072.4400000000005
      pressure: 7000.0
    - x: 0.093
      radius: 1.0
      velocity: 0.0
      temperature: 5063.385
      pressure: 7000.0
    - x: 0.094
      radius: 1.0
      velocity: 0.0
      temperature: 5054.33
      pressure: 7000.0
    - x: 0.095
      radius: 1.0
      velocity: 0.0
      temperature: 5045.275
      pressure: 7000.0
    - x: 0.096
      radius: 1.0
      velocity: 0.0
      temperature: 5036.22
      pressure: 7000.0
    - x: 0.097
      radius: 1.0
      velocity: 0.0
      temperature: 5027.165
      pressure: 7000.0
    - x: 0.098
      radius: 1.0
      velocity: 0.0
      temperature: 5018.11
      pressure: 7000.0
    - x: 0.099
      radius: 1.0
      velocity: 0.0
      temperature: 5009.055
      pressure: 7000.0
    - x: 0.1
      radius: 1.0
      velocity: 0.0
      temperature: 5000.0
      pressure: 7000.0
    velocity_gradient_stagnation: 4027.1213622326
    freestream_density: 0.0019382429
    freestream_velocity: 500000
    finite_thickness_params:
      v_edge: -111.31796
      d2_ue_dxdy: -290979.9698604651
      delta_bl: 0.010525
  wall_parameters:
    temperatures:
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    emissivity: 0
    environment_temperature: 300
