# =============================================================================
# CONTINUATION METHOD PARAMETERS FOR CONVERGENCE
# =============================================================================

continuation:
  wall_temperature_stable: 3000
  edge_temperature_stable: 5905.5
  pressure_stable: 7000

# =============================================================================
# BASE MODE
# =============================================================================

base:
  enabled: true
  simulation:
    body_type: axisymmetric
    only_stagnation_point: false
    finite_thickness: false
    diffusion_type: stefan_maxwell
    consider_thermal_diffusion: false
    consider_dufour_effect: false
    chemical_mode: non_equilibrium
    catalytic_wall: false
    wall_mode: imposed_temperature
  numerical:
    n_eta: 20
    eta_max: 6.0
    convergence_tolerance: 1.0e-09
    max_iterations: 100000
  mixture:
    name: CO2_5
    thermodynamic_database: RRHO
    viscosity_algorithm: chapman_enskog_ldlt
    thermal_conductivity_algorithm: chapman_enskog_ldlt
    state_model: ChemNonEq1T
  output:
    x_stations:
    - 0.0
    - 0.01
    - 0.02
    - 0.03
    - 0.04
    - 0.05
    - 0.06
    - 0.07
    - 0.08
    - 0.09
    - 0.1
    - 0.11
    - 0.12
    - 0.13
    - 0.14
    - 0.15
    - 0.16
    - 0.17
    - 0.18
    - 0.19
    - 0.2
    - 0.21
    - 0.22
    - 0.23
    - 0.24
    - 0.25
    - 0.26
    - 0.27
    - 0.28
    - 0.29
    - 0.3
    - 0.31
    - 0.32
    - 0.33
    - 0.34
    - 0.35000000000000003
    - 0.36
    - 0.37
    - 0.38
    - 0.39
    - 0.4
    - 0.41000000000000003
    - 0.42
    - 0.43
    - 0.44
    - 0.45
    - 0.46
    - 0.47000000000000003
    - 0.48
    - 0.49
    - 0.5
    - 0.51
    - 0.52
    - 0.53
    - 0.54
    - 0.55
    - 0.56
    - 0.5700000000000001
    - 0.58
    - 0.59
    - 0.6
    - 0.61
    - 0.62
    - 0.63
    - 0.64
    - 0.65
    - 0.66
    - 0.67
    - 0.68
    - 0.6900000000000001
    - 0.7000000000000001
    - 0.71
    - 0.72
    - 0.73
    - 0.74
    - 0.75
    - 0.76
    - 0.77
    - 0.78
    - 0.79
    - 0.8
    - 0.81
    - 0.8200000000000001
    - 0.8300000000000001
    - 0.84
    - 0.85
    - 0.86
    - 0.87
    - 0.88
    - 0.89
    - 0.9
    - 0.91
    - 0.92
    - 0.93
    - 0.9400000000000001
    - 0.9500000000000001
    - 0.96
    - 0.97
    - 0.98
    - 0.99
    - 1.0
    output_directory: test_outputs
  outer_edge:
    edge_points:
    - x: 0.0
      radius: 1.0
      velocity: 0.0
      temperature: 5905.5
      pressure: 7000.0
    - x: 0.01
      radius: 1.0
      velocity: 3.0
      temperature: 5916.445
      pressure: 7030.0
    - x: 0.02
      radius: 1.0
      velocity: 6.0
      temperature: 5927.39
      pressure: 7060.0
    - x: 0.03
      radius: 1.0
      velocity: 9.0
      temperature: 5938.335
      pressure: 7090.0
    - x: 0.04
      radius: 1.0
      velocity: 12.0
      temperature: 5949.28
      pressure: 7120.0
    - x: 0.05
      radius: 1.0
      velocity: 15.0
      temperature: 5960.225
      pressure: 7150.0
    - x: 0.06
      radius: 1.0
      velocity: 18.0
      temperature: 5971.17
      pressure: 7180.0
    - x: 0.07
      radius: 1.0
      velocity: 21.0
      temperature: 5982.115
      pressure: 7210.0
    - x: 0.08
      radius: 1.0
      velocity: 24.0
      temperature: 5993.06
      pressure: 7240.0
    - x: 0.09
      radius: 1.0
      velocity: 27.0
      temperature: 6004.005
      pressure: 7270.0
    - x: 0.1
      radius: 1.0
      velocity: 30.0
      temperature: 6014.95
      pressure: 7300.0
    - x: 0.11
      radius: 1.0
      velocity: 33.0
      temperature: 6025.895
      pressure: 7330.0
    - x: 0.12
      radius: 1.0
      velocity: 36.0
      temperature: 6036.84
      pressure: 7360.0
    - x: 0.13
      radius: 1.0
      velocity: 39.0
      temperature: 6047.785
      pressure: 7390.0
    - x: 0.14
      radius: 1.0
      velocity: 42.0
      temperature: 6058.73
      pressure: 7420.0
    - x: 0.15
      radius: 1.0
      velocity: 45.0
      temperature: 6069.675
      pressure: 7450.0
    - x: 0.16
      radius: 1.0
      velocity: 48.0
      temperature: 6080.62
      pressure: 7480.0
    - x: 0.17
      radius: 1.0
      velocity: 51.0
      temperature: 6091.565
      pressure: 7510.0
    - x: 0.18
      radius: 1.0
      velocity: 54.0
      temperature: 6102.51
      pressure: 7540.0
    - x: 0.19
      radius: 1.0
      velocity: 57.0
      temperature: 6113.455
      pressure: 7570.0
    - x: 0.2
      radius: 1.0
      velocity: 60.0
      temperature: 6124.4
      pressure: 7600.0
    - x: 0.21
      radius: 1.0
      velocity: 63.0
      temperature: 6135.345
      pressure: 7630.0
    - x: 0.22
      radius: 1.0
      velocity: 66.0
      temperature: 6146.29
      pressure: 7660.0
    - x: 0.23
      radius: 1.0
      velocity: 69.0
      temperature: 6157.235
      pressure: 7690.0
    - x: 0.24
      radius: 1.0
      velocity: 72.0
      temperature: 6168.18
      pressure: 7720.0
    - x: 0.25
      radius: 1.0
      velocity: 75.0
      temperature: 6179.125
      pressure: 7750.0
    - x: 0.26
      radius: 1.0
      velocity: 78.0
      temperature: 6190.07
      pressure: 7780.0
    - x: 0.27
      radius: 1.0
      velocity: 81.0
      temperature: 6201.015
      pressure: 7810.0
    - x: 0.28
      radius: 1.0
      velocity: 84.0
      temperature: 6211.96
      pressure: 7840.0
    - x: 0.29
      radius: 1.0
      velocity: 87.0
      temperature: 6222.905
      pressure: 7870.0
    - x: 0.3
      radius: 1.0
      velocity: 90.0
      temperature: 6233.85
      pressure: 7900.0
    - x: 0.31
      radius: 1.0
      velocity: 93.0
      temperature: 6244.795
      pressure: 7930.0
    - x: 0.32
      radius: 1.0
      velocity: 96.0
      temperature: 6255.74
      pressure: 7960.0
    - x: 0.33
      radius: 1.0
      velocity: 99.0
      temperature: 6266.685
      pressure: 7990.0
    - x: 0.34
      radius: 1.0
      velocity: 102.0
      temperature: 6277.63
      pressure: 8020.0
    - x: 0.35000000000000003
      radius: 1.0
      velocity: 105.0
      temperature: 6288.575
      pressure: 8050.0
    - x: 0.36
      radius: 1.0
      velocity: 108.0
      temperature: 6299.52
      pressure: 8080.0
    - x: 0.37
      radius: 1.0
      velocity: 111.0
      temperature: 6310.465
      pressure: 8110.0
    - x: 0.38
      radius: 1.0
      velocity: 114.0
      temperature: 6321.41
      pressure: 8140.0
    - x: 0.39
      radius: 1.0
      velocity: 117.0
      temperature: 6332.355
      pressure: 8170.0
    - x: 0.4
      radius: 1.0
      velocity: 120.0
      temperature: 6343.3
      pressure: 8200.0
    - x: 0.41000000000000003
      radius: 1.0
      velocity: 123.0
      temperature: 6354.245
      pressure: 8230.0
    - x: 0.42
      radius: 1.0
      velocity: 126.0
      temperature: 6365.19
      pressure: 8260.0
    - x: 0.43
      radius: 1.0
      velocity: 129.0
      temperature: 6376.135
      pressure: 8290.0
    - x: 0.44
      radius: 1.0
      velocity: 132.0
      temperature: 6387.08
      pressure: 8320.0
    - x: 0.45
      radius: 1.0
      velocity: 135.0
      temperature: 6398.025
      pressure: 8350.0
    - x: 0.46
      radius: 1.0
      velocity: 138.0
      temperature: 6408.97
      pressure: 8380.0
    - x: 0.47000000000000003
      radius: 1.0
      velocity: 141.0
      temperature: 6419.915
      pressure: 8410.0
    - x: 0.48
      radius: 1.0
      velocity: 144.0
      temperature: 6430.86
      pressure: 8440.0
    - x: 0.49
      radius: 1.0
      velocity: 147.0
      temperature: 6441.805
      pressure: 8470.0
    - x: 0.5
      radius: 1.0
      velocity: 150.0
      temperature: 6452.75
      pressure: 8500.0
    - x: 0.51
      radius: 1.0
      velocity: 153.0
      temperature: 6463.695
      pressure: 8530.0
    - x: 0.52
      radius: 1.0
      velocity: 156.0
      temperature: 6474.64
      pressure: 8560.0
    - x: 0.53
      radius: 1.0
      velocity: 159.0
      temperature: 6485.585
      pressure: 8590.0
    - x: 0.54
      radius: 1.0
      velocity: 162.0
      temperature: 6496.53
      pressure: 8620.0
    - x: 0.55
      radius: 1.0
      velocity: 165.0
      temperature: 6507.475
      pressure: 8650.0
    - x: 0.56
      radius: 1.0
      velocity: 168.0
      temperature: 6518.42
      pressure: 8680.0
    - x: 0.5700000000000001
      radius: 1.0
      velocity: 171.0
      temperature: 6529.365
      pressure: 8710.0
    - x: 0.58
      radius: 1.0
      velocity: 174.0
      temperature: 6540.31
      pressure: 8740.0
    - x: 0.59
      radius: 1.0
      velocity: 177.0
      temperature: 6551.255
      pressure: 8770.0
    - x: 0.6
      radius: 1.0
      velocity: 180.0
      temperature: 6562.2
      pressure: 8800.0
    - x: 0.61
      radius: 1.0
      velocity: 183.0
      temperature: 6573.145
      pressure: 8830.0
    - x: 0.62
      radius: 1.0
      velocity: 186.0
      temperature: 6584.09
      pressure: 8860.0
    - x: 0.63
      radius: 1.0
      velocity: 189.0
      temperature: 6595.035
      pressure: 8890.0
    - x: 0.64
      radius: 1.0
      velocity: 192.0
      temperature: 6605.98
      pressure: 8920.0
    - x: 0.65
      radius: 1.0
      velocity: 195.0
      temperature: 6616.925
      pressure: 8950.0
    - x: 0.66
      radius: 1.0
      velocity: 198.0
      temperature: 6627.87
      pressure: 8980.0
    - x: 0.67
      radius: 1.0
      velocity: 201.0
      temperature: 6638.8150000000005
      pressure: 9010.0
    - x: 0.68
      radius: 1.0
      velocity: 204.0
      temperature: 6649.76
      pressure: 9040.0
    - x: 0.6900000000000001
      radius: 1.0
      velocity: 207.0
      temperature: 6660.705
      pressure: 9070.0
    - x: 0.7000000000000001
      radius: 1.0
      velocity: 210.0
      temperature: 6671.65
      pressure: 9100.0
    - x: 0.71
      radius: 1.0
      velocity: 213.0
      temperature: 6682.595
      pressure: 9130.0
    - x: 0.72
      radius: 1.0
      velocity: 216.0
      temperature: 6693.54
      pressure: 9160.0
    - x: 0.73
      radius: 1.0
      velocity: 219.0
      temperature: 6704.485
      pressure: 9190.0
    - x: 0.74
      radius: 1.0
      velocity: 222.0
      temperature: 6715.43
      pressure: 9220.0
    - x: 0.75
      radius: 1.0
      velocity: 225.0
      temperature: 6726.375
      pressure: 9250.0
    - x: 0.76
      radius: 1.0
      velocity: 228.0
      temperature: 6737.32
      pressure: 9280.0
    - x: 0.77
      radius: 1.0
      velocity: 231.0
      temperature: 6748.265
      pressure: 9310.0
    - x: 0.78
      radius: 1.0
      velocity: 234.0
      temperature: 6759.21
      pressure: 9340.0
    - x: 0.79
      radius: 1.0
      velocity: 237.0
      temperature: 6770.155
      pressure: 9370.0
    - x: 0.8
      radius: 1.0
      velocity: 240.0
      temperature: 6781.1
      pressure: 9400.0
    - x: 0.81
      radius: 1.0
      velocity: 243.0
      temperature: 6792.045
      pressure: 9430.0
    - x: 0.8200000000000001
      radius: 1.0
      velocity: 246.0
      temperature: 6802.99
      pressure: 9460.0
    - x: 0.8300000000000001
      radius: 1.0
      velocity: 249.0
      temperature: 6813.935
      pressure: 9490.0
    - x: 0.84
      radius: 1.0
      velocity: 252.0
      temperature: 6824.88
      pressure: 9520.0
    - x: 0.85
      radius: 1.0
      velocity: 255.0
      temperature: 6835.825
      pressure: 9550.0
    - x: 0.86
      radius: 1.0
      velocity: 258.0
      temperature: 6846.77
      pressure: 9580.0
    - x: 0.87
      radius: 1.0
      velocity: 261.0
      temperature: 6857.715
      pressure: 9610.0
    - x: 0.88
      radius: 1.0
      velocity: 264.0
      temperature: 6868.66
      pressure: 9640.0
    - x: 0.89
      radius: 1.0
      velocity: 267.0
      temperature: 6879.605
      pressure: 9670.0
    - x: 0.9
      radius: 1.0
      velocity: 270.0
      temperature: 6890.55
      pressure: 9700.0
    - x: 0.91
      radius: 1.0
      velocity: 273.0
      temperature: 6901.495
      pressure: 9730.0
    - x: 0.92
      radius: 1.0
      velocity: 276.0
      temperature: 6912.4400000000005
      pressure: 9760.0
    - x: 0.93
      radius: 1.0
      velocity: 279.0
      temperature: 6923.385
      pressure: 9790.0
    - x: 0.9400000000000001
      radius: 1.0
      velocity: 282.0
      temperature: 6934.33
      pressure: 9820.0
    - x: 0.9500000000000001
      radius: 1.0
      velocity: 285.0
      temperature: 6945.275
      pressure: 9850.0
    - x: 0.96
      radius: 1.0
      velocity: 288.0
      temperature: 6956.22
      pressure: 9880.0
    - x: 0.97
      radius: 1.0
      velocity: 291.0
      temperature: 6967.165
      pressure: 9910.0
    - x: 0.98
      radius: 1.0
      velocity: 294.0
      temperature: 6978.110000000001
      pressure: 9940.0
    - x: 0.99
      radius: 1.0
      velocity: 297.0
      temperature: 6989.055
      pressure: 9970.0
    - x: 1.0
      radius: 1.0
      velocity: 300.0
      temperature: 7000.0
      pressure: 10000.0
    velocity_gradient_stagnation: 4027.1213622326
    freestream_density: 0.0019382429
    freestream_velocity: 500000
    finite_thickness_params:
      v_edge: -111.31796
      d2_ue_dxdy: -290979.9698604651
      delta_bl: 0.010525
  wall_parameters:
    temperatures:
    - 3000.0
    - 3020.0
    - 3040.0
    - 3060.0
    - 3080.0
    - 3100.0
    - 3120.0
    - 3140.0
    - 3160.0
    - 3180.0
    - 3200.0
    - 3220.0
    - 3240.0
    - 3260.0
    - 3280.0
    - 3300.0
    - 3320.0
    - 3340.0
    - 3360.0
    - 3380.0
    - 3400.0
    - 3420.0
    - 3440.0
    - 3460.0
    - 3480.0
    - 3500.0
    - 3520.0
    - 3540.0
    - 3560.0
    - 3580.0
    - 3600.0
    - 3620.0
    - 3640.0
    - 3660.0
    - 3680.0
    - 3700.0
    - 3720.0
    - 3740.0
    - 3760.0
    - 3780.0
    - 3800.0
    - 3820.0
    - 3840.0
    - 3860.0
    - 3880.0
    - 3900.0
    - 3920.0
    - 3940.0
    - 3960.0
    - 3980.0
    - 4000.0
    - 4020.0
    - 4040.0
    - 4060.0
    - 4080.0
    - 4100.0
    - 4120.0
    - 4140.0
    - 4160.0
    - 4180.0
    - 4200.0
    - 4220.0
    - 4240.0
    - 4260.0
    - 4280.0
    - 4300.0
    - 4320.0
    - 4340.0
    - 4360.0
    - 4380.0
    - 4400.0
    - 4420.0
    - 4440.0
    - 4460.0
    - 4480.0
    - 4500.0
    - 4520.0
    - 4540.0
    - 4560.0
    - 4580.0
    - 4600.0
    - 4620.0
    - 4640.0
    - 4660.0
    - 4680.0
    - 4700.0
    - 4720.0
    - 4740.0
    - 4760.0
    - 4780.0
    - 4800.0
    - 4820.0
    - 4840.0
    - 4860.0
    - 4880.0
    - 4900.0
    - 4920.0
    - 4940.0
    - 4960.0
    - 4980.0
    - 5000.0
    emissivity: 0
    environment_temperature: 300
