# =============================================================================
# CONTINUATION METHOD PARAMETERS FOR CONVERGENCE
# =============================================================================

continuation:
  wall_temperature_stable: 3000
  edge_temperature_stable: 5905.5
  pressure_stable: 7000

# =============================================================================
# BASE MODE
# =============================================================================

base:
  enabled: true
  simulation:
    body_type: axisymmetric
    only_stagnation_point: false
    finite_thickness: false
    diffusion_type: stefan_maxwell
    consider_thermal_diffusion: false
    consider_dufour_effect: false
    chemical_mode: non_equilibrium
    catalytic_wall: false
    wall_mode: imposed_temperature
  numerical:
    n_eta: 20
    eta_max: 6.0
    convergence_tolerance: 1.0e-09
    max_iterations: 100000
  mixture:
    name: CO2_5
    thermodynamic_database: RRHO
    viscosity_algorithm: chapman_enskog_ldlt
    thermal_conductivity_algorithm: chapman_enskog_ldlt
    state_model: ChemNonEq1T
  output:
    x_stations:
    - 0.0
    - 0.001
    - 0.002
    - 0.003
    - 0.004
    - 0.005
    - 0.006
    - 0.007
    - 0.008
    - 0.009000000000000001
    - 0.01
    - 0.011
    - 0.012
    - 0.013000000000000001
    - 0.014
    - 0.015
    - 0.016
    - 0.017
    - 0.018000000000000002
    - 0.019
    - 0.02
    - 0.021
    - 0.022
    - 0.023
    - 0.024
    - 0.025
    - 0.026000000000000002
    - 0.027
    - 0.028
    - 0.029
    - 0.03
    - 0.031
    - 0.032
    - 0.033
    - 0.034
    - 0.035
    - 0.036000000000000004
    - 0.037
    - 0.038
    - 0.039
    - 0.04
    - 0.041
    - 0.042
    - 0.043000000000000003
    - 0.044
    - 0.045
    - 0.046
    - 0.047
    - 0.048
    - 0.049
    - 0.05
    - 0.051000000000000004
    - 0.052000000000000005
    - 0.053
    - 0.054
    - 0.055
    - 0.056
    - 0.057
    - 0.058
    - 0.059000000000000004
    - 0.06
    - 0.061
    - 0.062
    - 0.063
    - 0.064
    - 0.065
    - 0.066
    - 0.067
    - 0.068
    - 0.069
    - 0.07
    - 0.07100000000000001
    - 0.07200000000000001
    - 0.073
    - 0.074
    - 0.075
    - 0.076
    - 0.077
    - 0.078
    - 0.079
    - 0.08
    - 0.081
    - 0.082
    - 0.083
    - 0.084
    - 0.085
    - 0.08600000000000001
    - 0.08700000000000001
    - 0.088
    - 0.089
    - 0.09
    - 0.091
    - 0.092
    - 0.093
    - 0.094
    - 0.095
    - 0.096
    - 0.097
    - 0.098
    - 0.099
    - 0.1
    output_directory: test_outputs
  outer_edge:
    edge_points:
    - x: 0.0
      radius: 1.0
      velocity: 0.0
      temperature: 5905.5
      pressure: 7000.0
    - x: 0.001
      radius: 1.0
      velocity: 1.0
      temperature: 5876.445
      pressure: 7000.0
    - x: 0.002
      radius: 1.0
      velocity: 2.0
      temperature: 5847.39
      pressure: 7000.0
    - x: 0.003
      radius: 1.0
      velocity: 3.0
      temperature: 5818.335
      pressure: 7000.0
    - x: 0.004
      radius: 1.0
      velocity: 4.0
      temperature: 5789.28
      pressure: 7000.0
    - x: 0.005
      radius: 1.0
      velocity: 5.0
      temperature: 5760.225
      pressure: 7000.0
    - x: 0.006
      radius: 1.0
      velocity: 6.0
      temperature: 5731.17
      pressure: 7000.0
    - x: 0.007
      radius: 1.0
      velocity: 7.0
      temperature: 5702.115
      pressure: 7000.0
    - x: 0.008
      radius: 1.0
      velocity: 8.0
      temperature: 5673.06
      pressure: 7000.0
    - x: 0.009000000000000001
      radius: 1.0
      velocity: 9.0
      temperature: 5644.005
      pressure: 7000.0
    - x: 0.01
      radius: 1.0
      velocity: 10.0
      temperature: 5614.95
      pressure: 7000.0
    - x: 0.011
      radius: 1.0
      velocity: 11.0
      temperature: 5585.895
      pressure: 7000.0
    - x: 0.012
      radius: 1.0
      velocity: 12.0
      temperature: 5556.84
      pressure: 7000.0
    - x: 0.013000000000000001
      radius: 1.0
      velocity: 13.0
      temperature: 5527.785
      pressure: 7000.0
    - x: 0.014
      radius: 1.0
      velocity: 14.0
      temperature: 5498.73
      pressure: 7000.0
    - x: 0.015
      radius: 1.0
      velocity: 15.0
      temperature: 5469.675
      pressure: 7000.0
    - x: 0.016
      radius: 1.0
      velocity: 16.0
      temperature: 5440.62
      pressure: 7000.0
    - x: 0.017
      radius: 1.0
      velocity: 17.0
      temperature: 5411.565
      pressure: 7000.0
    - x: 0.018000000000000002
      radius: 1.0
      velocity: 18.0
      temperature: 5382.51
      pressure: 7000.0
    - x: 0.019
      radius: 1.0
      velocity: 19.0
      temperature: 5353.455
      pressure: 7000.0
    - x: 0.02
      radius: 1.0
      velocity: 20.0
      temperature: 5324.4
      pressure: 7000.0
    - x: 0.021
      radius: 1.0
      velocity: 21.0
      temperature: 5295.345
      pressure: 7000.0
    - x: 0.022
      radius: 1.0
      velocity: 22.0
      temperature: 5266.29
      pressure: 7000.0
    - x: 0.023
      radius: 1.0
      velocity: 23.0
      temperature: 5237.235
      pressure: 7000.0
    - x: 0.024
      radius: 1.0
      velocity: 24.0
      temperature: 5208.18
      pressure: 7000.0
    - x: 0.025
      radius: 1.0
      velocity: 25.0
      temperature: 5179.125
      pressure: 7000.0
    - x: 0.026000000000000002
      radius: 1.0
      velocity: 26.0
      temperature: 5150.07
      pressure: 7000.0
    - x: 0.027
      radius: 1.0
      velocity: 27.0
      temperature: 5121.015
      pressure: 7000.0
    - x: 0.028
      radius: 1.0
      velocity: 28.0
      temperature: 5091.96
      pressure: 7000.0
    - x: 0.029
      radius: 1.0
      velocity: 29.0
      temperature: 5062.905
      pressure: 7000.0
    - x: 0.03
      radius: 1.0
      velocity: 30.0
      temperature: 5033.85
      pressure: 7000.0
    - x: 0.031
      radius: 1.0
      velocity: 31.0
      temperature: 5004.795
      pressure: 7000.0
    - x: 0.032
      radius: 1.0
      velocity: 32.0
      temperature: 4975.74
      pressure: 7000.0
    - x: 0.033
      radius: 1.0
      velocity: 33.0
      temperature: 4946.685
      pressure: 7000.0
    - x: 0.034
      radius: 1.0
      velocity: 34.0
      temperature: 4917.63
      pressure: 7000.0
    - x: 0.035
      radius: 1.0
      velocity: 35.0
      temperature: 4888.575
      pressure: 7000.0
    - x: 0.036000000000000004
      radius: 1.0
      velocity: 36.0
      temperature: 4859.52
      pressure: 7000.0
    - x: 0.037
      radius: 1.0
      velocity: 37.0
      temperature: 4830.465
      pressure: 7000.0
    - x: 0.038
      radius: 1.0
      velocity: 38.0
      temperature: 4801.41
      pressure: 7000.0
    - x: 0.039
      radius: 1.0
      velocity: 39.0
      temperature: 4772.355
      pressure: 7000.0
    - x: 0.04
      radius: 1.0
      velocity: 40.0
      temperature: 4743.3
      pressure: 7000.0
    - x: 0.041
      radius: 1.0
      velocity: 41.0
      temperature: 4714.245
      pressure: 7000.0
    - x: 0.042
      radius: 1.0
      velocity: 42.0
      temperature: 4685.1900000000005
      pressure: 7000.0
    - x: 0.043000000000000003
      radius: 1.0
      velocity: 43.0
      temperature: 4656.135
      pressure: 7000.0
    - x: 0.044
      radius: 1.0
      velocity: 44.0
      temperature: 4627.08
      pressure: 7000.0
    - x: 0.045
      radius: 1.0
      velocity: 45.0
      temperature: 4598.025
      pressure: 7000.0
    - x: 0.046
      radius: 1.0
      velocity: 46.0
      temperature: 4568.97
      pressure: 7000.0
    - x: 0.047
      radius: 1.0
      velocity: 47.0
      temperature: 4539.915
      pressure: 7000.0
    - x: 0.048
      radius: 1.0
      velocity: 48.0
      temperature: 4510.860000000001
      pressure: 7000.0
    - x: 0.049
      radius: 1.0
      velocity: 49.0
      temperature: 4481.805
      pressure: 7000.0
    - x: 0.05
      radius: 1.0
      velocity: 50.0
      temperature: 4452.75
      pressure: 7000.0
    - x: 0.051000000000000004
      radius: 1.0
      velocity: 51.0
      temperature: 4423.695
      pressure: 7000.0
    - x: 0.052000000000000005
      radius: 1.0
      velocity: 52.0
      temperature: 4394.64
      pressure: 7000.0
    - x: 0.053
      radius: 1.0
      velocity: 53.0
      temperature: 4365.585
      pressure: 7000.0
    - x: 0.054
      radius: 1.0
      velocity: 54.0
      temperature: 4336.53
      pressure: 7000.0
    - x: 0.055
      radius: 1.0
      velocity: 55.0
      temperature: 4307.475
      pressure: 7000.0
    - x: 0.056
      radius: 1.0
      velocity: 56.0
      temperature: 4278.42
      pressure: 7000.0
    - x: 0.057
      radius: 1.0
      velocity: 57.0
      temperature: 4249.365
      pressure: 7000.0
    - x: 0.058
      radius: 1.0
      velocity: 58.0
      temperature: 4220.3099999999995
      pressure: 7000.0
    - x: 0.059000000000000004
      radius: 1.0
      velocity: 59.0
      temperature: 4191.255
      pressure: 7000.0
    - x: 0.06
      radius: 1.0
      velocity: 60.0
      temperature: 4162.2
      pressure: 7000.0
    - x: 0.061
      radius: 1.0
      velocity: 61.0
      temperature: 4133.145
      pressure: 7000.0
    - x: 0.062
      radius: 1.0
      velocity: 62.0
      temperature: 4104.09
      pressure: 7000.0
    - x: 0.063
      radius: 1.0
      velocity: 63.0
      temperature: 4075.035
      pressure: 7000.0
    - x: 0.064
      radius: 1.0
      velocity: 64.0
      temperature: 4045.98
      pressure: 7000.0
    - x: 0.065
      radius: 1.0
      velocity: 65.0
      temperature: 4016.925
      pressure: 7000.0
    - x: 0.066
      radius: 1.0
      velocity: 66.0
      temperature: 3987.87
      pressure: 7000.0
    - x: 0.067
      radius: 1.0
      velocity: 67.0
      temperature: 3958.815
      pressure: 7000.0
    - x: 0.068
      radius: 1.0
      velocity: 68.0
      temperature: 3929.76
      pressure: 7000.0
    - x: 0.069
      radius: 1.0
      velocity: 69.0
      temperature: 3900.705
      pressure: 7000.0
    - x: 0.07
      radius: 1.0
      velocity: 70.0
      temperature: 3871.65
      pressure: 7000.0
    - x: 0.07100000000000001
      radius: 1.0
      velocity: 71.0
      temperature: 3842.595
      pressure: 7000.0
    - x: 0.07200000000000001
      radius: 1.0
      velocity: 72.0
      temperature: 3813.54
      pressure: 7000.0
    - x: 0.073
      radius: 1.0
      velocity: 73.0
      temperature: 3784.485
      pressure: 7000.0
    - x: 0.074
      radius: 1.0
      velocity: 74.0
      temperature: 3755.43
      pressure: 7000.0
    - x: 0.075
      radius: 1.0
      velocity: 75.0
      temperature: 3726.375
      pressure: 7000.0
    - x: 0.076
      radius: 1.0
      velocity: 76.0
      temperature: 3697.32
      pressure: 7000.0
    - x: 0.077
      radius: 1.0
      velocity: 77.0
      temperature: 3668.265
      pressure: 7000.0
    - x: 0.078
      radius: 1.0
      velocity: 78.0
      temperature: 3639.21
      pressure: 7000.0
    - x: 0.079
      radius: 1.0
      velocity: 79.0
      temperature: 3610.155
      pressure: 7000.0
    - x: 0.08
      radius: 1.0
      velocity: 80.0
      temperature: 3581.1
      pressure: 7000.0
    - x: 0.081
      radius: 1.0
      velocity: 81.0
      temperature: 3552.045
      pressure: 7000.0
    - x: 0.082
      radius: 1.0
      velocity: 82.0
      temperature: 3522.9900000000002
      pressure: 7000.0
    - x: 0.083
      radius: 1.0
      velocity: 83.0
      temperature: 3493.935
      pressure: 7000.0
    - x: 0.084
      radius: 1.0
      velocity: 84.0
      temperature: 3464.88
      pressure: 7000.0
    - x: 0.085
      radius: 1.0
      velocity: 85.0
      temperature: 3435.825
      pressure: 7000.0
    - x: 0.08600000000000001
      radius: 1.0
      velocity: 86.0
      temperature: 3406.77
      pressure: 7000.0
    - x: 0.08700000000000001
      radius: 1.0
      velocity: 87.0
      temperature: 3377.715
      pressure: 7000.0
    - x: 0.088
      radius: 1.0
      velocity: 88.0
      temperature: 3348.66
      pressure: 7000.0
    - x: 0.089
      radius: 1.0
      velocity: 89.0
      temperature: 3319.605
      pressure: 7000.0
    - x: 0.09
      radius: 1.0
      velocity: 90.0
      temperature: 3290.55
      pressure: 7000.0
    - x: 0.091
      radius: 1.0
      velocity: 91.0
      temperature: 3261.495
      pressure: 7000.0
    - x: 0.092
      radius: 1.0
      velocity: 92.0
      temperature: 3232.44
      pressure: 7000.0
    - x: 0.093
      radius: 1.0
      velocity: 93.0
      temperature: 3203.385
      pressure: 7000.0
    - x: 0.094
      radius: 1.0
      velocity: 94.0
      temperature: 3174.33
      pressure: 7000.0
    - x: 0.095
      radius: 1.0
      velocity: 95.0
      temperature: 3145.275
      pressure: 7000.0
    - x: 0.096
      radius: 1.0
      velocity: 96.0
      temperature: 3116.2200000000003
      pressure: 7000.0
    - x: 0.097
      radius: 1.0
      velocity: 97.0
      temperature: 3087.165
      pressure: 7000.0
    - x: 0.098
      radius: 1.0
      velocity: 98.0
      temperature: 3058.11
      pressure: 7000.0
    - x: 0.099
      radius: 1.0
      velocity: 99.0
      temperature: 3029.055
      pressure: 7000.0
    - x: 0.1
      radius: 1.0
      velocity: 100.0
      temperature: 3000.0
      pressure: 7000.0
    velocity_gradient_stagnation: 4027.1213622326
    freestream_density: 0.0019382429
    freestream_velocity: 500000
    finite_thickness_params:
      v_edge: -111.31796
      d2_ue_dxdy: -290979.9698604651
      delta_bl: 0.010525
  wall_parameters:
    temperatures:
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    emissivity: 0
    environment_temperature: 300
