# =============================================================================
# CONTINUATION METHOD PARAMETERS FOR CONVERGENCE
# =============================================================================

continuation:
  wall_temperature_stable: 3000
  edge_temperature_stable: 5905.5
  pressure_stable: 7000

# =============================================================================
# BASE MODE
# =============================================================================

base:
  enabled: true
  simulation:
    body_type: axisymmetric
    only_stagnation_point: false
    finite_thickness: false
    diffusion_type: stefan_maxwell
    consider_thermal_diffusion: false
    consider_dufour_effect: false
    chemical_mode: non_equilibrium
    catalytic_wall: false
    wall_mode: imposed_temperature
  numerical:
    n_eta: 20
    eta_max: 6.0
    convergence_tolerance: 1.0e-09
    max_iterations: 100000
  mixture:
    name: CO2_5
    thermodynamic_database: RRHO
    viscosity_algorithm: chapman_enskog_ldlt
    thermal_conductivity_algorithm: chapman_enskog_ldlt
    state_model: ChemNonEq1T
  output:
    x_stations:
      - 0.0
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      - 0.6
      - 0.7
      - 0.8
      - 0.9
      - 1.0
    output_directory: test_outputs
  outer_edge:
    edge_points:
    - x: 0.0
      radius: 1.0
      velocity: 0.0
      temperature: 5905.5
      pressure: 7000.0
    - x: 0.25
      radius: 1.0
      velocity: 25.0
      temperature: 5179.125
      pressure: 7000.0
    - x: 0.5
      radius: 1.0
      velocity: 50.0
      temperature: 4452.75
      pressure: 7000.0
    - x: 0.75
      radius: 1.0
      velocity: 75.0
      temperature: 3726.375
      pressure: 7000.0
    - x: 1.0
      radius: 1.0
      velocity: 100.0
      temperature: 3000.0
      pressure: 7000.0
    velocity_gradient_stagnation: 4027.1213622326
    freestream_density: 0.0019382429
    freestream_velocity: 500000
    finite_thickness_params:
      v_edge: -111.31796
      d2_ue_dxdy: -290979.9698604651
      delta_bl: 0.010525
  wall_parameters:
    temperatures:
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    - 3000.0
    emissivity: 0
    environment_temperature: 300
