simulation:
  body_type: axisymmetric
  only_stagnation_point: true
  diffusion_type: stefan_maxwell
  consider_thermal_diffusion: false
  consider_dufour_effect: false
  chemical_mode: "non_equilibrium" # "frozen" or "equilibrium" or "non_equilibrium"
  catalytic_wall: false

numerical:
  n_eta: 200                       
  eta_max: 6.0
  convergence_tolerance: 1.0e-9    
  max_iterations: 100000

mixture:
  name: CO2_5
  thermodynamic_database: RRHO
  viscosity_algorithm: chapman_enskog_ldlt
  state_model: ChemNonEq1T 

output:
  x_stations: [0.0]
  output_directory: test_outputs

outer_edge:
  edge_points:
    - x: 0.0
      radius: 1
      velocity: 0
      temperature: 5905.5
      pressure: 7000
  
  velocity_gradient_stagnation: 4027.1213622326
  freestream_density: 0.0019382429
  freestream_velocity: 500000

wall_parameters:
  temperatures: [2100]

abaque:
  enabled: false
  catalyticity_values: [0.0, 0.01]
  temperature_range: [3500, 5500]
  temperature_points: 20

continuation:
  wall_temperature_stable: 3000.0
  edge_temperature_stable: 5905.5
  pressure_stable: 7000.0

# ./blast config/default.yaml test_output
# python3 scripts/postprocess_blast.py --input test_outputs/simulation_20250713_232651.h5 --plots all --output results_h5
# python3 scripts/postprocess_blast_temperatures.py --input test_outputs/simulation_20250811_032725.h5 --plots all
# python3 scripts/postprocess_abaque.py --input test_outputs/simulation_abaque.h5