simulation:
  body_type: axisymmetric
  only_stagnation_point: true
  diffusion_type: stefan_maxwell
  consider_thermal_diffusion: false
  chemical_non_equilibrium: false  

numerical:
  n_eta: 100                       
  eta_max: 6.0
  convergence_tolerance: 1.0e-6    
  max_iterations: 2000000
  under_relaxation: 1
  step_control:
    lower_bound: 5
    upper_bound: 20
  solvers:
    h2t_tolerance: 1.0e-12
    h2t_max_iterations: 50000
    stefan_tolerance: 1.0e-12
    stefan_max_iterations: 50000

mixture:
  name: CO2_5
  thermodynamic_database: RRHO
  viscosity_algorithm: chapman_enskog_ldlt
  reference_temperature: 0.0

output:
  x_stations: [0.0]
  output_directory: test_outputs
  generate_lookup_table: false

outer_edge:
  edge_points:
    # Point de stagnation (x = 0.0)
    - x: 0.0
      radius: 1
      velocity: 0
      enthalpy: 1.429162e+07
      pressure: 7.000000e+03
      density: 2.912708e-03
      viscosity: 1.771427e-04
      species: [2.746334e-05, 5.391048e-01, 8.388689e-05, 4.190457e-01, 4.173816e-02]
  
  velocity_gradient_stagnation: 4027.1213622326
  freestream_density: 0.0019382429
  freestream_velocity: 500000

wall_parameters:
  temperatures: [3100]

# ./blast config/default.yaml test_output
# python3 scripts/postprocess_blast.py --input test_outputs/simulation_20250713_232651.h5 --plots all --output results_h5