simulation:
  body_type: axisymmetric
  only_stagnation_point: true
  diffusion_type: stefan_maxwell
  consider_thermal_diffusion: false
  chemical_mode: "non_equilibrium" # "frozen" or "equilibrium" or "non_equilibrium"
  catalytic_wall: true

numerical:
  n_eta: 20                       
  eta_max: 6.0
  convergence_tolerance: 1.0e-3    
  max_iterations: 5000

mixture:
  name: CO2_5
  thermodynamic_database: RRHO
  viscosity_algorithm: chapman_enskog_ldlt

output:
  x_stations: [0.0]
  output_directory: test_outputs

outer_edge:
  edge_points:
    - x: 0.0
      radius: 1
      velocity: 0
      temperature: 5905.5
      pressure: 7.000000e+03
  
  velocity_gradient_stagnation: 4027.1213622326
  freestream_density: 0.0019382429
  freestream_velocity: 500000

wall_parameters:
  temperatures: [300]

abaque:
  enabled: true
  catalyticity_values: [0.0, 0.1, 0.5, 1.0]
  temperature_range: [3000, 4000]
  temperature_points: 10

# ./blast config/default.yaml test_output
# python3 scripts/postprocess_blast.py --input test_outputs/simulation_20250713_232651.h5 --plots all --output results_h5