simulation:
  body_type: axisymmetric
  only_stagnation_point: false      # Résolution complète de la couche limite
  diffusion_type: stefan_maxwell
  consider_thermal_diffusion: false
  chemical_non_equilibrium: false  

numerical:
  n_eta: 20                       
  eta_max: 6.0
  convergence_tolerance: 1.0e-8    
  max_iterations: 10000
  under_relaxation: 1
  step_control:
    lower_bound: 5
    upper_bound: 20
  solvers:
    h2t_tolerance: 1.0e-8
    h2t_max_iterations: 50000
    stefan_tolerance: 1.0e-10
    stefan_max_iterations: 50000

mixture:
  name: air_5
  thermodynamic_database: RRHO
  viscosity_algorithm: chapman_enskog_ldlt
  reference_temperature: 0.0

output:
  x_stations: [0.0, 0.05, 0.1, 0.15, 0.2]
  output_directory: test_outputs
  generate_lookup_table: false

outer_edge:
  edge_points:
    # Point de stagnation (x = 0.0)
    - x: 0.0
      radius: 1.0
      velocity: 0.0
      enthalpy: 800000.0
      pressure: 1000.0
      density: 0.01
      viscosity: 2.0e-5
      species: [0.0, 0.0, 0.0, 0.767, 0.233]
    
    - x: 0.05
      radius: 1.0
      velocity: 10
      enthalpy: 800000.0
      pressure: 1000.0
      density: 0.01
      viscosity: 2.0e-5
      species: [0.0, 0.0, 0.0, 0.767, 0.233]
    
    - x: 0.1
      radius: 1.0
      velocity: 10
      enthalpy: 800000.0
      pressure: 1000.0
      density: 0.01
      viscosity: 2.0e-5
      species: [0.0, 0.0, 0.0, 0.767, 0.233]
    
    - x: 0.15
      radius: 1.0
      velocity: 10
      enthalpy: 800000.0
      pressure: 1000.0
      density: 0.01
      viscosity: 2.0e-5
      species: [0.0, 0.0, 0.0, 0.767, 0.233]

    - x: 0.2
      radius: 1.0
      velocity: 10
      enthalpy: 800000.0
      pressure: 1000.0
      density: 0.01
      viscosity: 2.0e-5
      species: [0.0, 0.0, 0.0, 0.767, 0.233]

  velocity_gradient_stagnation: 100000.0
  freestream_density: 0.01
  freestream_velocity: 3000.0

wall_parameters:
  temperatures: [500.0, 510.0, 520.0, 530.0, 540.0]