simulation:
  body_type: axisymmetric
  only_stagnation_point: true
  diffusion_type: stefan_maxwell
  consider_thermal_diffusion: false
  consider_dufour_effect: false
  chemical_mode: "non_equilibrium" # "frozen" or "equilibrium" or "non_equilibrium"
  catalytic_wall: false

numerical:
  n_eta: 20                       
  eta_max: 6.0
  convergence_tolerance: 1.0e-9    
  max_iterations: 100000

mixture:
  name: N2_1
  thermodynamic_database: RRHO
  viscosity_algorithm: chapman_enskog_ldlt
  thermal_conductivity_algorithm: chapman_enskog_ldlt
 

output:
  x_stations: [0.0]
  output_directory: test_outputs

outer_edge:
  edge_points:
    - x: 0.0
      radius: 1
      velocity: 0
      temperature: 3000
      pressure: 10000
      boundary_override: 
        enabled: false
        mass_fraction_condition: [0, 0.55, 0, 0.45, 0]
  
  velocity_gradient_stagnation: 4027.1213622326
  freestream_density: 0.0019382429
  freestream_velocity: 500000

wall_parameters:
  temperatures: [300]

abacus:
  enabled: false
  catalyticity_values: [0.0, 0.01]
  temperature_range: [3500, 5500]
  temperature_points: 20

continuation:
  wall_temperature_stable: 300.0
  edge_temperature_stable: 300.0
  pressure_stable: 10000